version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"

  - package-ecosystem: "npm"
    directory: "/client/randmovieapp"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
