version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
    links:
      - db
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_URL=mongodb://db:27017/randmovie
      - APP_PORT=80
    ports:
      - '80:3000'

  db:
    container_name: db
    image: mongo:4.0
    restart: always
    ports:
      - '27017:27017'

  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - server_URL=http://localhost/randmovie
